### PR TITLE
Handle parameter values with multiple entries

### LINKED ISSUE #634: Fails to parse COMMA-separated list of calendar addresses in quoted-strings (e.g. `MEMBER` parameter)
**RFC:** https://www.rfc-editor.org/rfc/rfc5545#section-3.2.11

The builtin ics parser does not handle parsing COMMA-separated list of calendar addresses in quoted-strings correctly.

**Note:** The ics example data (attendee property) is valid and was copied as is from the RFC.

## Example

```js
const ics = 'ATTENDEE;MEMBER="mailto:projectA@example.com","mailto:projectB@example.com":mailto:janedoe@example.com'
const prop = ICAL.Property.fromString(ics)
```

### Expected
```
[
  "attendee",
  {
    "member": [
      "mailto:projectA@example.com",
      "mailto:projectB@example.com"
    ]
  },
  "cal-address",
  "mailto:janedoe@example.com"
]
```

### Received
```
[
  "attendee",
  {
    "member": [
      "mailto:projectA@example.com",
      "mailto:projectB@example.com"
    ]
  },
  "cal-address",
  "projectA@example.com\",\"mailto:projectB@example.com\":mailto:janedoe@example.com"
]
```

The parser stops at the colon inside the first quoted-string `MEMBER` parameter. But for some reason both member parameters are still parsed correctly. Only the property value is not parsed correctly.

### PR DESCRIPTION
**Pull request by onny**
Fixing parser for quoted multi-value parameters. The PR fixes the string length detection of this parameter in case if it's not a simple single string but an array.

```
attendee = ICAL.Property.fromString(
  'ATTENDEE;MEMBER="mailto:mygroup@localhost","mailto:mygroup2@localhost":mailto:user2@localhost'
);
console.log(attendee);
```

Will now correctly return the attendee URI `mailto:user2@localhost`

Fixes https://github.com/kewisch/ical.js/issues/634

### CODE REVIEW

File: test/failure_test.js [hunk 1]
```diff
@@ -37,31 +37,4 @@ suite('Known failures', function() {
     assert.equal(subject.getParameter("cn"), "Z\\;");
     assert.equal(subject.getFirstValue(), "mailto:z@example.org");
   });
-
-  // Quoted multi-value parameters leak into the value
-  // Please see https://github.com/kewisch/ical.js/issues/634
-  testKnownFailure('with quoted multi-value parameter', function() {
```
Comment (mschroeder) [inline test/failure_test.js:43]: Shouldn't this test move to the normal testsuite with the bug been fixed?

File: lib/ical/parse.js [hunk 2]
```diff
@@ -165,7 +165,16 @@ parse._handleContentLine = function(line, state) {
       throw new ParserError("Invalid parameters in '" + line + "'");
     }
     params = parsedParams[0];
-    lastParamIndex = parsedParams[1].length + parsedParams[2] + paramPos;
+    // Handle parameter values with multiple entries
+    let parsedParamLength;
+    if (typeof parsedParams[1] === 'string') {
+      parsedParamLength = parsedParams[1].length;
+    } else {
+      parsedParamLength = parsedParams[1].reduce((accumulator, currentValue) => {
```
Comment (kewisch) [inline lib/ical/parse.js:173]: I'm suspecting we do most of the calculation for parameters within `_parseParameters` already and would like to see if we can optimize performance here a bit.

Could you instead use those numbers and return them as needed? It looks like `parsedParameters[2]` is only used to calculate `lastParamIndex`, so we could change the meaning of this field in the array to include the parsed param length.

Comment (kewisch) [reply lib/ical/parse.js:173]: While you are at it, can you update the return value in jsdoc for `_parseParameters` ? It simply says an object with key/value right now.

File: test/failure_test.js (hunk 1 above)
Comment (kewisch) [reply test/failure_test.js:43]: Agree on this, let's move it to `parse_test.js`

**Review by kewisch — CHANGES_REQUESTED** [review]
Thank you for taking a stab at this! Parsing is one of the paths that I'd like to keep optimized as much as JS makes it possible, I'd appreciate if you could take a look at the following comments. Let me know if you have any questions!

**Review by kewisch — APPROVED** [review]

**Comment by kewisch** [comment]
Thanks for the patience and taking care of the comments!
