### PR TITLE
fix bug when using VALUE param to set type of property. closes #35

### LINKED ISSUE #35: TRIGGER as DATE-TIME causes parser error
Example:

```
TRIGGER;VALUE=DATE-TIME:20120903T233000Z
```

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

File: lib/ical/parser.js [hunk 1]
```diff
@@ -249,8 +249,12 @@
     }
 
     if ("parameters" in aLineData && "VALUE" in aLineData.parameters) {
-      ICAL.helpers.dumpn("VAAAA: " + aLineData.parameters.VALUE.toString());
-      valueType = aLineData.parameters.VALUE.toUpperCase();
+      var valueParam = aLineData.parameters.VALUE;
+      if (typeof(valueParam) === 'string') {
```
Comment (lightsofapollo) [inline lib/ical/parser.js:253]: I believe this case is impossible? but I wanted to preserve the original behavior if it was intentional but did not cover the case where the param is an object... I admit I didn't dig into it very deeply.

Comment (kewisch) [inline lib/ical/parser.js:253]: I don't know off hand either, but it won't hurt.
